apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test-runner-state
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: server
      value: testmanager.4epjg.mongodb.net
    - name: username
      value: testmanager
    - name: password
      value: 98kh7Wx5xBGoHyUM
    - name: databaseName
      value: TestRunnerDev
    - name: collectionName
      value: testrunner
    - name: actorStateStore
      value: true
    - name: operationTimeout
      value: 10s
    - name: writeConcern
      value: majority