name: backoffice-int
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "!backend/VietGeeks.TestPlatform.TestManager.Functions.SendEmail/**"
env:
  CONTAINER_APP_NAME: backoffice-api
  CONTAINER_APP_ENVIRONMENT: tranchy-cae-testplatf-dev-sa
  CONTAINER_APP_RESOURCE_GROUP_NAME: tranchy-rg-testplatform-wrong-southeastasia
  CONTAINER_APP_RESOURCE_GROUP_LOCATION: southeastasia
  CONTAINER_REGISTRY_LOGIN_SERVER: TranchyAcrTestPlatfDevSa.azurecr.io
  CONTAINER_REGISTRY_USERNAME: TranchyAcrTestPlatfDevSa
  DOCKER_FILE_PATH: backend/Dockerfile
  PROJECT_NAME_FOR_DOCKER: backoffice-api
  CONTAINER_APP_IDENTITY: tranchy-uai-backoffice-dev-sa
  CONTAINER_APP_CERTIFICATE: tranchy-cae-testplatf-dev-sa-testportal-api-certificate
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run VietGeeks.TestPlatform.TestManager.UnitTest
        run: dotnet test ./backend/VietGeeks.TestPlatform.TestManager.UnitTest/VietGeeks.TestPlatform.TestManager.UnitTest.csproj
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{env.CONTAINER_REGISTRY_USERNAME}}
          password: ${{ secrets.TranchyAcrTestPlatfDevSa_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          target: final-backoffice
          tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
          file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.tranchy-rg-testplatform-dev-southeastasia_SPN }}
      - name: checkout
        uses: actions/checkout@v4
      - name: Deploy to containerapp
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          template: ./deployment/container-app-backoffice-api.bicep
          parameters: location=${{ env.CONTAINER_APP_RESOURCE_GROUP_LOCATION }} environmentName=${{ env.CONTAINER_APP_ENVIRONMENT }} containerAppName=${{ env.CONTAINER_APP_NAME }} containerImage=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} containerRegistry=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} userAssignedIdentity=${{ env.CONTAINER_APP_IDENTITY }} subDomainCertificate=${{ env.CONTAINER_APP_CERTIFICATE }}
          failOnStdErr: false
          deploymentName: backoffice-int-${{ github.sha }}
      - name: logout
        run: >
          az logout
