name: Push to Azure Container Registry
on:
  push:
    branches:
      - master
jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}
          
      - name: Update build version    
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MINOR'
          value: $((${{ secrets.MINOR }}+1))
          repository: 'Viet-Geeks'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          org: true
          visibility: 'all'
          
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: |   
          docker-compose build
        working-directory: ./TestPlatform/src
        
      - name: Push Docker image to Azure Container Registry
        run: |
            docker tag vietgeeks.testplatform.testmanager.webapp:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.webapp:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
            docker tag vietgeeks.testplatform.testmanager.api:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.api:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.webapp:${{ secrets.MAJOR }}.${{ secrets.MINOR }}     
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.api:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
