name: Push to Azure Container Registry
on:
  push:
    branches:
      - master
jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}
          
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: |   
          docker-compose build
        working-directory: ./TestPlatform/src
        
      - name: Push Docker image to Azure Container Registry
        run: |
            $version = ${{ secrets.MAJOR }}+"."+(0000+$($Env:GITHUB_RUN_NUMBER))
            docker tag vietgeeks.testplatform.testmanager.webapp:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.webapp:$version
            docker tag vietgeeks.testplatform.testmanager.api:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.api:$version
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.webapp:$version     
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/vietgeeks.testplatform.testmanager.api:$version
