name: Dev:Test-Runner-WebApp Static WebApp

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "TestPlatform/src/Services/TestRunner/VietGeeks.TestPlatform.TestRunner.WebApp/**"
      - "TestPlatform/src/Services/TestManager/VietGeeks.TestPlatform.TestManager.WebApp/ClientApp/apps/test-runner/**"
env:
  NPM_CONFIG_FORCE: true
  NPM_CONFIG_LEGACY_PEER_DEPS: true
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV_TEST_RUNNER_APP }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: /github/workspace/TestPlatform/src/Services/TestManager/VietGeeks.TestPlatform.TestManager.WebApp/ClientApp
          app_build_command: "npm run build:test-runner"
          output_location: /github/workspace/TestPlatform/src/Services/TestManager/VietGeeks.TestPlatform.TestManager.WebApp/ClientApp/dist/apps/test-runner
